### ISSUE TITLE
JSON::Any is being phased out

### ISSUE THREAD

**Issue by karenetheridge** [b10m/p5-Dancer2-Plugin-Auth-OAuth#1]
JSON::Any is being phased out in favour of JSON::MaybeXS, which handles the edge cases more gracefully - you probably want to switch to that, unless you rely on some of the legacy stuff (e.g. JSON::DWIM and ::Syck support) in JSON::Any.

**Comment by b10m** [comment]
Patched in [0d35f2c19a03d7ff6250c54309a3df22cb34eae0](https://github.com/b10m/p5-Dancer2-Plugin-Auth-OAuth/commit/0d35f2c19a03d7ff6250c54309a3df22cb34eae0)

Thanks!
