### ISSUE TITLE
`UsingUnmatched ) in regex;` 500 error

### ISSUE THREAD

**Issue by drmuey** [b10m/p5-Dancer2-Plugin-Auth-OAuth#12]
perl v5.016000
Dancer2 v0.205001
Dancer2::Plugin::Auth::OAuth v0.12

1. add use statement per POD
2. add config.yml per POD
3. plackup bin/app.psgi 
4. hit http://localhost:5000/
5. get a 500 error:
`Unmatched ) in regex; marked by <-- HERE in m/^\/auth [(?#splat)([^\/]+) <-- HERE ]\/stackexchange$/ at /Users/dmuey/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/Dancer2/Core/Route.pm line 85.`

In case it was a YAML typo I also removed the space before `[*]` in the example config and the same error occurs (w/ the error's `auth [(` becoming `auth[(` of course).

**Comment by drmuey** [comment]
ah, the ` [*]` is a footnote indicator. Would you be interested in a pull request that clarifies that example?

If not, at least this issue can serve as a help to anyone else that hits this after pasting in the example ;)

**Comment by b10m** [comment]
Sure, go ahead :)
