### ISSUE TITLE
Ability to get users locale

### ISSUE THREAD

**Issue by drmuey** [b10m/p5-Dancer2-Plugin-Auth-OAuth#13]
Twitter gives us `lang` (and possibly `location` as the Territory part).

Facebook gives us `locale` if we add `locale` to the CSV of the `fields` field.

Google does not return that info by default :(

Haven't tested any others yet but ideally they would all be able to incldue their locale preference and the sample config would reflect how to do so.

Thanks!

**Comment by b10m** [comment]
That should all be possible by simply adding them to the fields list of the config, as you said. A link to all options in the docs is fine with me, I look forward to the PR ;-)
