### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [b10m/p5-Dancer2-Plugin-Auth-OAuth#2]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by b10m** [comment]
Fixed in 5c43ad0177c6e84bfa00ac796670e4193a61d9c3
