### ISSUE TITLE
It needs LWP::Protocol::https

### ISSUE THREAD

**Issue by biafra** [b10m/p5-Dancer2-Plugin-Auth-OAuth#5]
After some time not understanding why I was receiving a callback and was always redirected for a failed route a bit of debug on the response showed:

"LWP will support https URLs if the LWP::Protocol::https module\nis installed.\n"

_msg => "Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)",

It should be added as a pre-requisit.

**Comment by b10m** [comment]
Thanks!
